### ISSUE TITLE
ERROR:electrumx:ElectrumX server terminated abnormally

### ISSUE THREAD

**Issue by agideo-code** [lucky2077/atomicals-electrumx-docker#14]
Image Version

```
# docker images | grep atomicals-electrumx
lucky2077/atomicals-electrumx         latest    1e715599e684   2 days ago    128MB
# date
Fri Dec 29 02:34:41 AM UTC 2023
```

uname -a
```
Linux s569-zj01 5.15.0-89-generic #99-Ubuntu SMP Mon Oct 30 20:42:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

Error Log

```
f7f9bf343b60966a6e8e5a8a5024f579e9d06d98154736f4d7a17f0c223f576db885a38ef5a7b9166b9f060000000000
INFO:BlockProcessor:atomicals_undo_entry_len -6 - count 44 - 130
INFO:Prefetcher:cancelled; prefetcher stopping
INFO:Controller:shutting down
INFO:Controller:shutdown complete
ERROR:electrumx:ElectrumX server terminated abnormally
Traceback (most recent call last):
  File "/electrumx/electrumx_server", line 35, in main
    asyncio.run(controller.run())
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/electrumx/electrumx/lib/server_base.py", line 129, in run
    await server_task
  File "/electrumx/electrumx/lib/server_base.py", line 102, in serve
    await self.serve(shutdown_event)
  File "/electrumx/electrumx/server/controller.py", line 137, in serve
    await group.spawn(wait_for_catchup())
  File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/electrumx/electrumx/server/block_processor.py", line 3582, in fetch_and_process_blocks
    await group.spawn(self._process_prefetched_blocks())
  File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 297, in __aexit__
    await self.join()
  File "/electrumx/electrumx/lib/util.py", line 370, in join
    task.result()
  File "/electrumx/electrumx/server/block_processor.py", line 3542, in _process_prefetched_blocks
    await self.check_and_advance_blocks(blocks)
  File "/electrumx/electrumx/server/block_processor.py", line 323, in check_and_advance_blocks
    await self.reorg_chain()
  File "/electrumx/electrumx/server/block_processor.py", line 365, in reorg_chain
    await self.run_in_thread_with_lock(self.backup_blocks, raw_blocks)
  File "/electrumx/electrumx/server/block_processor.py", line 295, in run_in_thread_with_lock
    return await asyncio.shield(run_in_thread_locked())
  File "/electrumx/electrumx/server/block_processor.py", line 294, in run_in_thread_locked
    return await run_in_thread(func, *args)
  File "/usr/local/lib/python3.9/site-packages/aiorpcx/curio.py", line 57, in run_in_thread
    return await get_event_loop().run_in_executor(None, func, *args)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/electrumx/electrumx/server/block_processor.py", line 3130, in backup_blocks
    self.backup_txs(block.transactions, is_unspendable)
  File "/electrumx/electrumx/server/block_processor.py", line 3303, in backup_txs
    assert(c >= 0)
AssertionError
```

**Comment by huangsmalldragon** [comment]
我也出现这个问题，请问您怎么解决的？

**Comment by agideo-code** [comment]
最后发现是IP配置问题，看日志

**Comment by agideo-code** [comment]
还有就是 重新索引
